Mess/urls.py
from django.conf.urls import url
from django.contrib import admin
from .import views

app_name ='Mess'

urlpatterns = [
    url(r'^h/$',views.home,name='index'),
    url(r'^hi/$',views.oye,name='index'),
    url(r'^login_user/$',views.login_user,name='login_user'),
   	url(r'^adddata/$',views.adddata,name='adddata'),
   	url(r'^logout/',views.logout,name='logout')
   # url(r'^display/$',views.display,name='display'),
    # url(r'^index/$',views.index,name='index'),

]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/',include('Mess.urls')),

]

Mess/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Extras(models.Model):
	roll_no = models.CharField(max_length =20)
	date  =  models.DateField()
	item = models.CharField(max_length =50)
	quantity = models.IntegerField(default=0)
	extra =models.IntegerField(default=0)

class UserProfile(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
	roll_no = models.CharField(max_length=10)
	reg_no = models.CharField(max_length=10)
	extra = models.IntegerField(default=0)
	type_id =models.CharField(max_length=20)
	mess = models.CharField(max_length=2,default='A')

class items(models.Model):
	name = models.CharField(max_length=50)
	cost = models.IntegerField(default=0)
	mess = models.CharField(max_length=2,default='A')

Mess/forms.py
class ExtrasForm(forms.ModelForm):

    class Meta:
        model = Extras
        fields = ['roll_no', 'date', 'item', 'quantity']

Mess/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from .models import UserProfile
from .models import items
from .models import Extras
from django.views.decorators.csrf import csrf_exempt
from django.utils import six
from itertools import product,chain
from django.utils.deprecation import (
    DeprecationInstanceCheck, RemovedInDjango20Warning,
)

# Create your views here.

def home(request):
	return render(request,'Mess/hi.html')
def oye(request):
	return HttpResponse('<h1> Bye </h1>')

@csrf_exempt
def login_user(request):
    if request.method == "POST":
        username = request.POST['name']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        login(request,user)
        u = request.user
        if request.user.is_authenticated():
        	me = UserProfile.objects.filter(user=u)
	        typeid = me[0].type_id
	        amount = me[0].extra
	        rollno = me[0].roll_no
	        if user is not None:
	            if user.is_active:
	            	if typeid == "Student":# cheking whether user is student or Mess member
	            		 context={'roll':rollno,'amount':amount }
	            		 print(context)
	            		 obj=Extras.objects.filter(roll_no=rollno)#Multiple Rows having data
	            		 obj2=UserProfile.objects.filter(roll_no=rollno)
	            		 result_list=list(chain(obj,obj2))
	            		 #print(obj)
	            		 return render(request, 'Mess/display.html',{'obj': result_list})#rendering to Display.html
	            	else:
	                	return render(request, 'Mess/adddata.html')#rendering to adddata from where to URL Then to adddata function
	            else:
	                return render(request, 'Mess/studentln.html', {'error_message': 'Your account has been disabled'})#Error MEssage
	        else:
	            return render(request, 'Mess/studentln.html', {'error_message': 'Invalid login'})#error Message
    return render(request, 'Mess/studentln.html',{})#Rendering back to same page


@csrf_exempt
def adddata(request):
	if request.method =="POST":
		item=request.POST['Item']
		roll=request.POST['roll']
		qty=request.POST['quantity']
		date=request.POST['Date']
		obj1=UserProfile.objects.get(roll_no=roll)
		obj= items.objects.get(name = item , mess =obj1.mess)
		price=obj.cost*float(qty)
		obj2 = Extras(roll_no=roll, date=date, item=item ,quantity=qty,extra=price)
		obj2.save()
		obj1.extra=float(obj1.extra)+float(price)
		obj1.save()	
	return render(request,'Mess/adddata.html')


@csrf_exempt
def logout(request):
	return render(request,'Mess/login_user.html')
	
# def index(request,me):
# 	print("inindex")
# 	if me[0].type_id=="Student":
# 		roll= me[0].roll_no
# 		reg = me[0].reg_no
# 		amount = me[0].extra
# 		print(amount)
# 		display(request)
# 		return render(request, 'Mess/display.html')
# 	else:
# 		adddata(request)
# 		return render(request,'Mess/adddata.html')

# def display(request):
# 	return HttpResponse("HII Bro")

	# item=request.POST['item']
 #        roll=request.POST['roll']
 #        qty=request.POST['quantity']
 #        date=request.POST['Date']
 #        obj=items.objects.get(name=item)
 #        price=obj.cost*float(qty)
 #        obj1=UserProfile.objects.get(roll_no=roll)
 #        obj1.extra=float(obj1.extra)+float(price)
 #        obj1.save()
	# item=request.POST['Item']
	# 	roll=request.POST['roll']
	# 	qty=request.POST['quantity']
	# 	date=request.POST['Date']
	#     obj= items.objects.get(name = item)
	# 	price=obj.cost*float(qty)
	# 	obj2 = Extras(roll_no=roll, date=date, item=item ,quantity=qty,amount=price)
	# 	obj2.save()
	# 	obj1=UserProfile.objects.get(roll_no=roll)
	# 	obj1.extra=float(obj1.extra)+float(price)
	# 	obj1.save()

Mess/templates/Mess/MessAdmin.html
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>Mess Extras</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="bootstrap/js/bootstrap.min.js"></script>
    </head>
    <body>
         
        <div class="panel panel-body col-xs-4">
  <div class="panel-body">
      <img src="img/logoi.jpg" alt="WSDC" style=" height: 60%; width: 60%; padding-bottom: 20px; float: left;">
            <form>
        
  <div class="form-group" style=" float: left;">
    <label for="name">Name</label>
        <input type="text" name="name" class="field" id="name">
  </div>
                <div class="form-group" style="float: left;">
    <label for="roll">Roll no.</label>
    <input type="text" name="roll" class="field" required pattern="[a-zA-Z0-9]+" id="roll">
  </div>
 
  <button type="submit" class="btn btn-default">Submit</button>
  </form>
  </div>
 
  
  
    </body>
</html>

Mess/templates/Mess/adddata.html
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Mess Extras</title>
        <link rel="icon" type="image/jpg" href="img/lol.jpg" >
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="bootstrap/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="style/cs.css">
    </head>
    <body style=" background-image: url('img/cover.jpg'); background-size: 100% 100%;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-position: center; ">
        

        <div class="container">
    <h1>Mess</h1>
  </div>

  <div class="container"> 
    <div class="jumbotron">
      <div class="jumbotron-content">
        <h1>Administrator Portal</h1>
        <p class="jumbotron-lg-only">Please enter the following details.</p>
        <form action="{% url 'Mess:adddata'%}" method="post" enctype="multipart/form-data">

          
          <div class="form-group">
            <label for="roll">Roll Number:</label>
            <input type="text" name="roll" class="form-control" placeholder="roll">
          </div>
            <div class="form-group">
            <label for="Date">Date</label>
            <input type="date" name="Date" class="form-control" placeholder="dd-mm-yyyy">
          </div>
            <div class="form-group">
                <label for="Items">Items</label>
                <select name="Item">
                    <option>Chicken Dry</option>
                    <option>Chicken Masala</option>
                    <option>Eggs</option>
                    <option>Fruit Juice</option>
                    <option>Samosa</option>
                </select>
           <!--        <label for="Item">Item</label>
                  <input type="text" name="Item" class="form-control" placeholder=""> -->


                <div class="form-group">
                    <label for="quantity">Quantity</label>
            <input type="number" name="quantity" class="form-control" placeholder="quantity">
          </div>
                
            </div>
            
               
           
                
  
              
                
                
          <!-- <a href="sumbit" class="pull-right btn btn-default">submit</a> -->
           <input type="submit" value="submit" name="submit">
        </form>
      </div>
  </div>
  </div>


</body>
    
</html>

Mess/templates/Mess/display.html
<!DOCTYPE html>
<html>
<head>
	<title>Result</title>
                <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="newcss.css">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
</head>
<body>
        <div class="container">
            <div class="table-responsive">
            <table class="table table-stripped table-bordered table-hover std">
                <tbody>
	<tr>
            <th>Date</th><th>Roll No</th><th>Total Of a Day</th><br></tr>
	{% for i in obj %}
        <tr><td>{{i.date}}</td><td>{{i.roll_no}}</td><td>{{i.extra}}</td></tr>
	
	{% endfor %}
</tbody>
<<!-- /table>
<br><br><br>
              <table class="table table-stripped table-bordered table-hover std">
                <tbody>
	<tr>
          <th>Roll No</th><th>Total</th><br></tr>
        <tr><td>{{roll}}</td><td>{{amount}}</td></tr>
	
</tbody>
</table> -->
   




            </div>
        </div>
</body>
</html>

Mess/templates/Mess/hi.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<P>chvyugrsgfm,.bkdjlgbkl cobijfgmncbifhrekfsdhtrbn </P>


</form>
</body>
</html>

Mess/templates/Mess/index.html
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>Mess Extras</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="bootstrap/js/bootstrap.min.js"></script>
    </head>
    <body>
         
        <div class="panel panel-body col-xs-4 col-xs-offset-4" style="padding-left: 50px;">
  <div class="panel-body">
        <img src="img/logoi.jpg" alt="WSDC">
            <form   role="form" action="{% url 'Mess:login_user'%}" method="post" enctype="multipart/form-data">
        
  <div class="form-group">
    <label for="name">Name</label>
        <input type="text" name="name" class="field" id="name">
  </div>
  <div class="form-group">
    <label for="roll">Password:</label>
    <input type="Password" name="Password" class="field" required pattern="[a-zA-Z0-9]+" id="Password">
  </div>
 
  <button type="submit" class="btn btn-default">Submit</button>
  </form>
  </div>
  
  
    </body>
</html>

Mess/templates/Mess/studentln.html
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Mess Extras</title>
        <link rel="icon" type="image/jpg" href="img/lol.jpg" >
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="bootstrap/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="style/cs.css">
    </head>
    <body>
        
<div class="fakenavbar">
  <div class="container">
    <h2>Mess</h2>
  </div>
</div>

  <div class="container"> 
    <div class="jumbotron">
      <div class="jumbotron-content">
        <h1>Mess Portal</h1>
        <p class="jumbotron-xs-6">Please Login</p>
        <form name="user-info" action="{% url 'Mess:login_user'%}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
          <div class="form-group">
            <label for="name">Name</label>
            <input type="text" name="name" class="form-control" placeholder="Name">
          </div>
          <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" name="password" class="form-control" placeholder="Password">
          </div>
          <input type="submit" value="submit" name="submit
          ">
        </form >
      </div>
      <!--<p class="img-credit">Image Dynamically Provided by <a href="http://lorempixel.com">LoremPixel</a></p>-->
    </div>
    
    <!--<h2>Remaining Content...</h2>-->
  </div>

<div class="fakefooter">
  
</div>
</body>
    
</html>

Mess/templates/Mess/test.html
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>Mess Extras</title>
        <link rel="icon" type="image/jpg" href="img/lol.jpg" >
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="bootstrap/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="style/cs.css">
    </head>
    <body>
        <div style=" padding-left: 10px; padding-top: 20px; ">
        <div class="panel panel-body col-xs-4 col-xs-offset-4" style=" padding-left: 20px; padding-top: 40px; border: 2px solid black;" >
  <div class="panel-body">
      &emsp;&emsp;&emsp;
      <img src="img/logoi.jpg" alt="WSDC" style=" height: 60%; width: 60%; padding-bottom: 20px; ">
            <form>
        
  <div class="form-group">
    <label for="name">Name</label>
    &emsp;&nbsp;  &nbsp; &nbsp;&nbsp;&nbsp;
        <input type="text" name="name" class="field" id="name">
  </div>
                <div class="form-group" >
    <label for="roll">Roll no.</label>
    &nbsp; &nbsp;      &emsp;
    <input type="text" name="roll" class="field" required pattern="[a-zA-Z0-9]+" id="roll" >
  </div>
 
                <button type="submit" class="btn btn-default" >Submit</button>
            </form>
      </div>
  
  </div>

        </div>
        
  
        </body>
    
</html>